# -*- coding: utf-8 -*-
"""Pengpol 6_Ghozi Alvin Karim_121450123.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s04Vak33f0FS-ayVBApJ52Dp63lj-SfH

# TUGAS PENGENALAN POLA
---
> Nama : Ghozi Alvin Karim \\
> Nim : 121450123  \\
> Kelas : Pengenalan Pola (RA)
---

## Scale Invariant Feature Transform (SIFT) & Speeded-Up Robust Features (SURF)
"""

!pip install opencv-python opencv-python-headless
! pip install opencv-contrib-python

import cv2
import numpy as np
import matplotlib.pyplot as plt

def detect_and_match(img1, img2, method='sift'):
    if method == 'sift':
        detector = cv2.SIFT_create()
    elif method == 'surf':
        detector = cv2.ORB_create()
    else:
        raise ValueError("Method should be 'sift' or 'surf'")

    # Deteksi keypoints dan deskriptor
    kp1, des1 = detector.detectAndCompute(img1, None)
    kp2, des2 = detector.detectAndCompute(img2, None)

    # Pencocokan fitur
    if method == 'sift':
        matcher = cv2.BFMatcher()
        matches = matcher.knnMatch(des1, des2, k=2)

        # Aplikasikan rasio tes
        good_matches = []
        for m, n in matches:
            if m.distance < 0.75 * n.distance:
                good_matches.append(m)
    else:  # surf
        bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
        good_matches = bf.match(des1, des2)
        good_matches = sorted(good_matches, key=lambda x: x.distance)

    return kp1, kp2, good_matches

# Fungsi untuk visualisasi
def visualize_matches(img1, kp1, img2, kp2, matches):
    img_matches = cv2.drawMatches(img1, kp1, img2, kp2, matches, None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    plt.figure(figsize=(15, 5))
    plt.imshow(cv2.cvtColor(img_matches, cv2.COLOR_BGR2RGB))
    plt.title(f'Feature Matches ({len(matches)} matches)')
    plt.axis("on")
    plt.show()

# Data
img1 = cv2.imread('/content/drive/MyDrive/Data Pengpol/permainanbolabaskket.jpeg', cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread('/content/drive/MyDrive/Data Pengpol/ringbasket.jpeg', cv2.IMREAD_GRAYSCALE)

results = compare_methods(img1, img2)

"""## Time, Accuracy dan robustness"""

# Fungsi untuk analisis perbandingan
def compare_methods(img1, img2):
    methods = ['sift','surf']
    results = {}

    for method in methods:
        start_time = cv2.getTickCount()
        kp1, kp2, matches = detect_and_match(img1, img2, method)
        end_time = cv2.getTickCount()

        processing_time = (end_time - start_time) / cv2.getTickFrequency()

        results[method] = {
            'time': processing_time,
            'matches': len(matches),
            'keypoints1': len(kp1),
            'keypoints2': len(kp2)
        }

        visualize_matches(img1, kp1, img2, kp2, matches[:50])  # Visualisasi 50 pencocokan terbaik

    return results

# Tampilkan hasil perbandingan
for method, result in results.items():
    print(f"\nMetode: {method.upper()}")
    print(f"Waktu pemrosesan: {result['time']:.4f} detik")
    print(f"Jumlah keypoints (gambar 1): {result['keypoints1']}")
    print(f"Jumlah keypoints (gambar 2): {result['keypoints2']}")
    print(f"Jumlah pencocokan: {result['matches']}")